server:
  port: '9093'

spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/microservice?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: ORDER-SERVICE

  boot:
    admin:
      client:
        url: http://localhost:1111/


management:
  endpoints:
    web:
      exposure:
        include: '*'


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
